# Generated by Django 3.1.4 on 2021-03-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210329_1004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orderd_Item',
        ),
    ]
